spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html
  mvc:
    format:
      date: yyyy-MM-dd
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  type-aliases-package: com.wang.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
